In [55]:
import pandas as pd
import matplotlib.pyplot as plt
import pylab
import scipy.stats as stats
import numpy as np
from collections import OrderedDict
import numpy as np
import datetime as dt

In [70]:
folderPath = 'C:\\Users\\Benjamin\\Desktop\\Storm_allyears\\Storm_allyears.csv'
df = pd.read_csv(folderPath)
print(df)

C:\Users\Benjamin\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (2,4,8,9,10,11,14,15,16,17,18,20,21,22,23,24,25,26,29,32,33,34,35) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

               EVENT_TYPE CZ_TYPE CZ_FIPS     CZ_NAME  WFO  \
0                 Tornado       C     149     WASHITA  NaN
1                 Tornado       C      93    COMANCHE  NaN
2                 Tornado       C      77      LEHIGH  NaN
3                 Tornado       C      43     DAUPHIN  NaN
4                 Tornado       C      39    CRAWFORD  NaN
5                 Tornado       C      17       BUCKS  NaN
6                 Tornado       C      71   LANCASTER  NaN
7                 Tornado       C      11       BERKS  NaN
8                 Tornado       C      63      HUGHES  NaN
9                 Tornado       C     121   PITTSBURG  NaN
10                Tornado       C      25    CIMARRON  NaN
11                Tornado       C     129    NUCKOLLS  NaN
12                Tornado       C     109    OKLAHOMA  NaN
13                Tornado       C     121   PITTSBURG  NaN
14                Tornado       C      81     LINCOLN  NaN
15                Tornado       C     143       TULSA  NaN
16                Tornado       C      75       KIOWA  NaN
17                Tornado       C      75       KIOWA  NaN
18                Tornado       C      63      HUGHES  NaN
19                Tornado       C      29        COAL  NaN
20                Tornado       C      39      CUSTER  NaN
21                Tornado       C       9     BECKHAM  NaN
22                Tornado       C     153    WOODWARD  NaN
23                Tornado       C      45       ELLIS  NaN
24                Tornado       C     119       PAYNE  NaN
25                Tornado       C      73  KINGFISHER  NaN
26                Tornado       C     121      RANKIN  NaN
27                Tornado       C     121      RANKIN  NaN
28                Tornado       C      25        CLAY  NaN
29                Tornado       C     141  TISHOMINGO  NaN
...                   ...     ...     ...         ...  ...
973086              Flood       C      69     FLEMING  JKL
973087        Flash Flood       C      23  SANTA CRUZ  TWC
973088  Thunderstorm Wind       C      77     GREELEY  GID
973089               Hail       C      77     GREELEY  GID
973090  Thunderstorm Wind       C      35     FORREST  JAN
973091  Thunderstorm Wind       C      53   HUMPHREYS  JAN
973092        Flash Flood       C      35     FORREST  JAN
973093  Thunderstorm Wind       C      29      COPIAH  JAN
973094  Thunderstorm Wind       C      85     LINCOLN  JAN
973095        Flash Flood       C      43    HERKIMER  ALY
973096        Flash Flood       C      43    HERKIMER  ALY
973097  Thunderstorm Wind       C     211    HEMPHILL  AMA
973098               Hail       C      65      CARSON  AMA
973099               Hail       C     179        GRAY  AMA
973100              Flood       C      17   MIDDLESEX  BOX
973101               Hail       C     175      VALLEY  GID
973102        Flash Flood       C      43    HERKIMER  ALY
973103  Thunderstorm Wind       C      59     JACKSON  LIX
973104        Flash Flood       C      85     LINCOLN  JAN
973105  Thunderstorm Wind       C      19        PIMA  TWC
973106  Thunderstorm Wind       C     141      PENDER  ILM
973107               Hail       C      31      CORSON  ABR
973108               Hail       C      45     EDMUNDS  ABR
973109               Hail       C      13       BROWN  ABR
973110               Hail       C      41        CLAY  FSD
973111               Hail       C     119        LYON  FSD
973112               Hail       C     143     OSCEOLA  FSD
973113  Thunderstorm Wind       C      73   SAN DIEGO  SGX
973114        Flash Flood       C      73   SAN DIEGO  SGX
973115        Flash Flood       C      73   SAN DIEGO  SGX

           BEGIN_DATE_TIME CZ_TIMEZONE       END_DATE_TIME INJURIES_DIRECT  \
0       28-APR-50 14:45:00         CST  28-APR-50 14:45:00               0
1       29-APR-50 15:30:00         CST  29-APR-50 15:30:00               0
2       05-JUL-50 18:00:00         CST  05-JUL-50 18:00:00               2
3       05-JUL-50 18:30:00         CST  05-JUL-50 18:30:00               0
4       24-JUL-50 14:40:00         CST  24-JUL-50 14:40:00               0
5       29-AUG-50 16:00:00         CST  29-AUG-50 16:00:00               0
6       04-NOV-50 17:00:00         CST  04-NOV-50 17:00:00               1
7       04-NOV-50 17:30:00         CST  04-NOV-50 17:30:00               0
8       15-SEP-50 17:45:00         CST  15-SEP-50 17:45:00               6
9       16-SEP-50 01:30:00         CST  16-SEP-50 01:30:00               0
10      01-OCT-50 21:00:00         CST  01-OCT-50 21:00:00               0
11      22-JUN-50 21:00:00         CST  22-JUN-50 21:00:00               0
12      27-FEB-50 10:20:00         CST  27-FEB-50 10:20:00               0
13      27-MAR-50 03:00:00         CST  27-MAR-50 03:00:00               0
14      02-APR-50 18:00:00         CST  02-APR-50 18:00:00               0
15      03-APR-50 16:15:00         CST  03-APR-50 16:15:00               0
16      28-APR-50 14:17:00         CST  28-APR-50 14:17:00               1
17      28-APR-50 14:35:00         CST  28-APR-50 14:35:00               0
18      28-APR-50 19:05:00         CST  28-APR-50 19:05:00              32
19      28-APR-50 19:30:00         CST  28-APR-50 19:30:00               0
20      04-MAY-50 21:30:00         CST  04-MAY-50 21:30:00               0
21      04-MAY-50 21:30:00         CST  04-MAY-50 21:30:00               0
22      04-MAY-50 21:45:00         CST  04-MAY-50 21:45:00               0
23      07-MAY-50 18:30:00         CST  07-MAY-50 18:30:00               0
24      07-MAY-50 23:00:00         CST  07-MAY-50 23:00:00               0
25      07-MAY-50 23:00:00         CST  07-MAY-50 23:00:00               3
26      27-MAR-50 08:00:00         CST  27-MAR-50 08:00:00               0
27      27-MAR-50 08:05:00         CST  27-MAR-50 08:05:00               0
28      27-MAR-50 08:45:00         CST  27-MAR-50 08:45:00               0
29      27-MAR-50 11:00:00         CST  27-MAR-50 11:00:00               2
...                    ...         ...                 ...             ...
973086  23-JUL-17 02:40:00       EST-5  23-JUL-17 04:30:00               0
973087  17-JUL-17 05:30:00       MST-7  17-JUL-17 06:05:00               0
973088  08-JUL-17 17:11:00       CST-6  08-JUL-17 17:11:00               0
973089  08-JUL-17 17:40:00       CST-6  08-JUL-17 17:40:00               0
973090  07-JUL-17 16:10:00       CST-6  07-JUL-17 16:10:00               0
973091  08-JUL-17 08:28:00       CST-6  08-JUL-17 08:28:00               0
973092  24-JUL-17 07:02:00       CST-6  24-JUL-17 09:15:00               0
973093  24-JUL-17 09:40:00       CST-6  24-JUL-17 09:47:00               0
973094  24-JUL-17 10:18:00       CST-6  24-JUL-17 10:18:00               0
973095  01-JUL-17 12:00:00       EST-5  01-JUL-17 15:30:00               0
973096  01-JUL-17 15:00:00       EST-5  01-JUL-17 15:30:00               0
973097  03-JUL-17 18:24:00       CST-6  03-JUL-17 18:24:00               0
973098  03-JUL-17 19:05:00       CST-6  03-JUL-17 19:05:00               0
973099  03-JUL-17 19:43:00       CST-6  03-JUL-17 19:43:00               0
973100  12-JUL-17 17:00:00       EST-5  12-JUL-17 22:00:00               0
973101  02-JUL-17 15:20:00       CST-6  02-JUL-17 15:20:00               0
973102  01-JUL-17 15:10:00       EST-5  01-JUL-17 15:30:00               0
973103  25-JUL-17 12:00:00       CST-6  25-JUL-17 12:00:00               0
973104  25-JUL-17 07:27:00       CST-6  25-JUL-17 09:15:00               0
973105  13-JUL-17 19:25:00       MST-7  13-JUL-17 19:35:00               0
973106  06-JUL-17 13:30:00       EST-5  06-JUL-17 13:31:00               0
973107  05-JUL-17 16:20:00       MST-7  05-JUL-17 16:20:00               0
973108  05-JUL-17 17:26:00       CST-6  05-JUL-17 17:26:00               0
973109  05-JUL-17 17:48:00       CST-6  05-JUL-17 17:48:00               0
973110  21-AUG-17 01:05:00       CST-6  21-AUG-17 01:05:00               0
973111  21-AUG-17 10:48:00       CST-6  21-AUG-17 10:48:00               0
973112  21-AUG-17 10:57:00       CST-6  21-AUG-17 10:57:00               0
973113  12-AUG-17 16:25:00       PST-8  12-AUG-17 16:35:00               0
973114  12-AUG-17 16:30:00       PST-8  12-AUG-17 17:30:00               0
973115  12-AUG-17 16:10:00       PST-8  12-AUG-17 18:00:00               0

       INJURIES_INDIRECT   ...    BEGIN_RANGE BEGIN_AZIMUTH  \
0                      0   ...              0           NaN
1                      0   ...              0           NaN
2                      0   ...              0           NaN
3                      0   ...              0           NaN
4                      0   ...              0           NaN
5                      0   ...              0           NaN
6                      0   ...              0           NaN
7                      0   ...              0           NaN
8                      0   ...              0           NaN
9                      0   ...              0           NaN
10                     0   ...              0           NaN
11                     0   ...              0           NaN
12                     0   ...              0           NaN
13                     0   ...              0           NaN
14                     0   ...              0           NaN
15                     0   ...              0           NaN
16                     0   ...              0           NaN
17                     0   ...              0           NaN
18                     0   ...              0           NaN
19                     0   ...              0           NaN
20                     0   ...              0           NaN
21                     0   ...              0           NaN
22                     0   ...              0           NaN
23                     0   ...              0           NaN
24                     0   ...              0           NaN
25                     0   ...              0           NaN
26                     0   ...              0           NaN
27                     0   ...              0           NaN
28                     0   ...              0           NaN
29                     0   ...              0           NaN
...                  ...   ...            ...           ...
973086                 0   ...              1           WSW
973087                 0   ...              1           WSW
973088                 0   ...              0             N
973089                 0   ...              1             E
973090                 0   ...              1            SE
973091                 0   ...              1             S
973092                 0   ...              4           SSW
973093                 0   ...              2           SSW
973094                 0   ...              4           WSW
973095                 0   ...              1            SE
973096                 0   ...              3            NW
973097                 0   ...              6           ENE
973098                 0   ...              1             E
973099                 0   ...              1           NNE
973100                 0   ...              1            SW
973101                 0   ...              5           ENE
973102                 0   ...              1           NNW
973103                 0   ...              1           SSW
973104                 0   ...              2           WNW
973105                 0   ...              2            SW
973106                 0   ...              1            NW
973107                 0   ...              5           ESE
973108                 0   ...              3           NNE
973109                 0   ...              0             E
973110                 0   ...              3           ENE
973111                 0   ...              1             E
973112                 0   ...              2             E
973113                 0   ...              4            SE
973114                 0   ...              3            SE
973115                 0   ...              8             S

              BEGIN_LOCATION END_RANGE END_AZIMUTH          END_LOCATION  \
0                        NaN         0         NaN                   NaN
1                        NaN         0         NaN                   NaN
2                        NaN         0         NaN                   NaN
3                        NaN         0         NaN                   NaN
4                        NaN         0         NaN                   NaN
5                        NaN         0         NaN                   NaN
6                        NaN         0         NaN                   NaN
7                        NaN         0         NaN                   NaN
8                        NaN         0         NaN                   NaN
9                        NaN         0         NaN                   NaN
10                       NaN         0         NaN                   NaN
11                       NaN         0         NaN                   NaN
12                       NaN         0         NaN                   NaN
13                       NaN         0         NaN                   NaN
14                       NaN         0         NaN                   NaN
15                       NaN         0         NaN                   NaN
16                       NaN         0         NaN                   NaN
17                       NaN         0         NaN                   NaN
18                       NaN         0         NaN                   NaN
19                       NaN         0         NaN                   NaN
20                       NaN         0         NaN                   NaN
21                       NaN         0         NaN                   NaN
22                       NaN         0         NaN                   NaN
23                       NaN         0         NaN                   NaN
24                       NaN         0         NaN                   NaN
25                       NaN         0         NaN                   NaN
26                       NaN         0         NaN                   NaN
27                       NaN         0         NaN                   NaN
28                       NaN         0         NaN                   NaN
29                       NaN         0         NaN                   NaN
...                      ...       ...         ...                   ...
973086     FLEMINGSBURG ARPT         0          SW     FLEMINGSBURG ARPT
973087               NOGALES         1         WSW               NOGALES
973088               WOLBACH         0           N               WOLBACH
973089                SCOTIA         1           E                SCOTIA
973090                 MAXIE         1          SE                 MAXIE
973091               BELZONI         1           S               BELZONI
973092                CARNES         4         SSW                CARNES
973093            HAZLEHURST         1           N            HAZLEHURST
973094             NEW SIGHT         4         WSW             NEW SIGHT
973095               NEWPORT         1         SSE               NEWPORT
973096            EATONVILLE         3           S           MIDDLEFIELD
973097              CANADIAN         6         ENE              CANADIAN
973098            SKELLYTOWN         1           E            SKELLYTOWN
973099                 PAMPA         1         NNE                 PAMPA
973100  (BED)HANSCOM FLD BED         1          SW  (BED)HANSCOM FLD BED
973101                   ORD         5         ENE                   ORD
973102         WEST SCHUYLER         2           W                HARBOR
973103       OCEAN SPGS ARPT         1         SSW       OCEAN SPGS ARPT
973104  BROOKHAVEN MUNI ARPT         1         WSW  BROOKHAVEN MUNI ARPT
973105             GREEN VLY         1           N           CONTINENTAL
973106              WOODSIDE         1          NW              WOODSIDE
973107               WAKPALA         5         ESE               WAKPALA
973108                  MINA         3         NNE                  MINA
973109                  BATH         0           E                  BATH
973110               DICKENS         3         ENE               DICKENS
973111           ROCK RAPIDS         1           E           ROCK RAPIDS
973112                SIBLEY         2           E                SIBLEY
973113    AGUA CALIENTE SPGS         5          SE    AGUA CALIENTE SPGS
973114    AGUA CALIENTE SPGS         5          SE    AGUA CALIENTE SPGS
973115        OCOTILLO WELLS         5          NE    AGUA CALIENTE SPGS

       BEGIN_LAT BEGIN_LON  END_LAT  END_LON
0          35.12    -99.20    35.17   -99.20
1          31.90    -98.60    31.73   -98.60
2          40.58    -75.70    40.65   -75.47
3          40.60    -76.75      NaN      NaN
4          41.63    -79.68      NaN      NaN
5          40.22    -75.00      NaN      NaN
6          40.20    -76.12    40.27   -76.07
7          40.27    -76.07    40.40   -75.93
8          35.00    -96.25    35.07   -96.17
9          34.83    -95.85      NaN      NaN
10         36.73   -102.52    36.88  -102.30
11         40.18    -98.03    40.20   -97.98
12         35.55    -97.60      NaN      NaN
13         34.85    -95.75      NaN      NaN
14         35.82    -97.02      NaN      NaN
15         36.13    -95.83      NaN      NaN
16         34.88    -99.28    35.00   -99.20
17         35.00    -99.20    35.12   -99.20
18         35.08    -96.40    35.13   -96.35
19         34.55    -96.20      NaN      NaN
20         35.58    -99.17      NaN      NaN
21         35.25    -99.55    35.32   -99.50
22         36.57    -99.57      NaN      NaN
23         36.30    -99.80      NaN      NaN
24         36.00    -97.00      NaN      NaN
25         36.12    -97.83    36.17   -97.78
26         32.30    -90.12    32.98   -89.82
27         32.30    -90.17    32.48   -89.78
28         33.67    -88.78    33.72   -88.73
29         34.73    -88.27      NaN      NaN
...          ...       ...      ...      ...
973086   38.4269   -83.742  38.4271 -83.7347
973087   31.3416  -110.951  31.3415 -110.951
973088      41.4     -98.4     41.4    -98.4
973089     41.47  -98.7007    41.47 -98.7007
973090     30.96    -89.19    30.96   -89.19
973091     33.17     -90.5    33.17    -90.5
973092     30.92    -89.29  30.9237 -89.3015
973093     31.84    -90.41    31.89    -90.4
973094   31.6173  -90.5096  31.6173 -90.5096
973095   43.1644  -75.0016  43.1645 -75.0068
973096     43.11    -74.98  43.1115 -74.9886
973097     35.92   -100.28    35.92  -100.28
973098     35.57   -101.17    35.57  -101.17
973099     35.55   -100.96    35.55  -100.96
973100   42.4637  -71.2925  42.4636 -71.2904
973101   41.6277  -98.8406  41.6277 -98.8406
973102   43.1083  -75.1561   43.083 -75.1884
973103    30.371  -88.7567   30.371 -88.7567
973104   31.6087  -90.4256  31.5932 -90.4168
973105   31.8849  -110.995  31.8611 -110.978
973106   34.4283  -77.6802  34.4286 -77.6803
973107     45.65   -100.44    45.65  -100.44
973108     45.47    -98.75    45.47   -98.75
973109     45.47    -98.32    45.47   -98.32
973110     43.14    -94.97    43.14   -94.97
973111     43.43    -96.17    43.43   -96.17
973112      43.4    -95.73     43.4   -95.73
973113   32.9156  -116.244  32.9008 -116.239
973114   32.9181  -116.254  32.8959 -116.253
973115   33.0425  -116.105  32.9962 -116.231

[973116 rows x 36 columns]

In [71]:
print(df.columns)

Index(['EVENT_TYPE', 'CZ_TYPE', 'CZ_FIPS', 'CZ_NAME', 'WFO', 'BEGIN_DATE_TIME',
       'CZ_TIMEZONE', 'END_DATE_TIME', 'INJURIES_DIRECT', 'INJURIES_INDIRECT',
       'DEATHS_DIRECT', 'DEATHS_INDIRECT', 'DAMAGE_PROPERTY', 'DAMAGE_CROPS',
       'SOURCE', 'MAGNITUDE', 'MAGNITUDE_TYPE', 'FLOOD_CAUSE', 'CATEGORY',
       'TOR_F_SCALE', 'TOR_LENGTH', 'TOR_WIDTH', 'TOR_OTHER_WFO',
       'TOR_OTHER_CZ_STATE', 'TOR_OTHER_CZ_FIPS', 'TOR_OTHER_CZ_NAME',
       'BEGIN_RANGE', 'BEGIN_AZIMUTH', 'BEGIN_LOCATION', 'END_RANGE',
       'END_AZIMUTH', 'END_LOCATION', 'BEGIN_LAT', 'BEGIN_LON', 'END_LAT',
       'END_LON'],
      dtype='object')

In [72]:
# Delete unused columns
del df['CZ_FIPS']
del df['CZ_TYPE']
del df['WFO']
del df['END_DATE_TIME']
del df['CZ_TIMEZONE']
del df['SOURCE']
del df['MAGNITUDE']
del df['MAGNITUDE_TYPE']
del df['FLOOD_CAUSE']
del df['CATEGORY']
del df['TOR_F_SCALE']
del df['TOR_LENGTH']
del df['TOR_WIDTH']
del df['TOR_OTHER_WFO']
del df['TOR_OTHER_CZ_STATE']
del df['TOR_OTHER_CZ_FIPS']
del df['TOR_OTHER_CZ_NAME']
del df['BEGIN_RANGE']
del df['BEGIN_AZIMUTH']
del df['BEGIN_LOCATION']
del df['END_RANGE']
del df['END_AZIMUTH']
del df['END_LOCATION']
del df['END_LAT']
del df['END_LON']
print(df.columns)

Index(['EVENT_TYPE', 'CZ_NAME', 'BEGIN_DATE_TIME', 'INJURIES_DIRECT',
       'INJURIES_INDIRECT', 'DEATHS_DIRECT', 'DEATHS_INDIRECT',
       'DAMAGE_PROPERTY', 'DAMAGE_CROPS', 'BEGIN_LAT', 'BEGIN_LON'],
      dtype='object')

In [75]:
df['DEATHS'] = df['DEATHS_DIRECT'] + df['DEATHS_INDIRECT']
df['INJURIES'] = df['INJURIES_INDIRECT'] + df['INJURIES_DIRECT']
df=df.rename(columns = {'BEGIN_DATE_TIME':'DATE'})
df=df.rename(columns = {'CZ_NAME':'NAME'})

del df['DEATHS_DIRECT']
del df['DEATHS_INDIRECT']
del df['INJURIES_INDIRECT']
del df['INJURIES_DIRECT']

print(df.columns)

Index(['EVENT_TYPE', 'NAME', 'DATE', 'DAMAGE_PROPERTY', 'DAMAGE_CROPS',
       'BEGIN_LAT', 'BEGIN_LON', 'DEATHS', 'INJURIES'],
      dtype='object')

In [76]:
# Remove any rows that match the header row
df = df[df.EVENT_TYPE != 'EVENT_TYPE']

In [79]:
print(df['DATE'])

0         28-APR-50 14:45:00
1         29-APR-50 15:30:00
2         05-JUL-50 18:00:00
3         05-JUL-50 18:30:00
4         24-JUL-50 14:40:00
5         29-AUG-50 16:00:00
6         04-NOV-50 17:00:00
7         04-NOV-50 17:30:00
8         15-SEP-50 17:45:00
9         16-SEP-50 01:30:00
10        01-OCT-50 21:00:00
11        22-JUN-50 21:00:00
12        27-FEB-50 10:20:00
13        27-MAR-50 03:00:00
14        02-APR-50 18:00:00
15        03-APR-50 16:15:00
16        28-APR-50 14:17:00
17        28-APR-50 14:35:00
18        28-APR-50 19:05:00
19        28-APR-50 19:30:00
20        04-MAY-50 21:30:00
21        04-MAY-50 21:30:00
22        04-MAY-50 21:45:00
23        07-MAY-50 18:30:00
24        07-MAY-50 23:00:00
25        07-MAY-50 23:00:00
26        27-MAR-50 08:00:00
27        27-MAR-50 08:05:00
28        27-MAR-50 08:45:00
29        27-MAR-50 11:00:00
                 ...
973086    23-JUL-17 02:40:00
973087    17-JUL-17 05:30:00
973088    08-JUL-17 17:11:00
973089    08-JUL-17 17:40:00
973090    07-JUL-17 16:10:00
973091    08-JUL-17 08:28:00
973092    24-JUL-17 07:02:00
973093    24-JUL-17 09:40:00
973094    24-JUL-17 10:18:00
973095    01-JUL-17 12:00:00
973096    01-JUL-17 15:00:00
973097    03-JUL-17 18:24:00
973098    03-JUL-17 19:05:00
973099    03-JUL-17 19:43:00
973100    12-JUL-17 17:00:00
973101    02-JUL-17 15:20:00
973102    01-JUL-17 15:10:00
973103    25-JUL-17 12:00:00
973104    25-JUL-17 07:27:00
973105    13-JUL-17 19:25:00
973106    06-JUL-17 13:30:00
973107    05-JUL-17 16:20:00
973108    05-JUL-17 17:26:00
973109    05-JUL-17 17:48:00
973110    21-AUG-17 01:05:00
973111    21-AUG-17 10:48:00
973112    21-AUG-17 10:57:00
973113    12-AUG-17 16:25:00
973114    12-AUG-17 16:30:00
973115    12-AUG-17 16:10:00
Name: DATE, dtype: object

In [80]:
def ExtractYear(date):
    date = str(date)
    part = date.split('-')
    shortYear = part[2][0:2]
    if int(shortYear) >= 50:
        return '19'+str(shortYear)
    else:
        return '20'+str(shortYear)
    
df['YEAR'] = [ExtractYear(date) for date in df['DATE']] 
print(df['YEAR'])

0         1950
1         1950
2         1950
3         1950
4         1950
5         1950
6         1950
7         1950
8         1950
9         1950
10        1950
11        1950
12        1950
13        1950
14        1950
15        1950
16        1950
17        1950
18        1950
19        1950
20        1950
21        1950
22        1950
23        1950
24        1950
25        1950
26        1950
27        1950
28        1950
29        1950
          ...
973086    2017
973087    2017
973088    2017
973089    2017
973090    2017
973091    2017
973092    2017
973093    2017
973094    2017
973095    2017
973096    2017
973097    2017
973098    2017
973099    2017
973100    2017
973101    2017
973102    2017
973103    2017
973104    2017
973105    2017
973106    2017
973107    2017
973108    2017
973109    2017
973110    2017
973111    2017
973112    2017
973113    2017
973114    2017
973115    2017
Name: YEAR, dtype: object

In [81]:
#https://www.ncdc.noaa.gov/cag/national/time-series/110-tavg-3-3-1950-2018.csv?base_prd=true&begbaseyear=1901&endbaseyear=2000
folderPath = 'C:\\Users\\Benjamin\\Desktop\\Storm_allyears\\Monthly_Temperatures.txt'
temps = pd.read_csv(folderPath)
del temps['Anomaly']
temps.columns = ['YEAR', 'TEMPERATURE']
temps['YEAR'] = [str(s)[0:4] for s in temps['YEAR']]
#print(pd.concat([df, temps], join='inner', axis = 1))
df = df.merge(temps, on = 'YEAR', how = 'inner')
print(df)

               EVENT_TYPE        NAME                DATE DAMAGE_PROPERTY  \
0                 Tornado     WASHITA  28-APR-50 14:45:00            250K
1                 Tornado    COMANCHE  29-APR-50 15:30:00             25K
2                 Tornado      LEHIGH  05-JUL-50 18:00:00             25K
3                 Tornado     DAUPHIN  05-JUL-50 18:30:00            2.5K
4                 Tornado    CRAWFORD  24-JUL-50 14:40:00            2.5K
5                 Tornado       BUCKS  29-AUG-50 16:00:00            2.5K
6                 Tornado   LANCASTER  04-NOV-50 17:00:00            250K
7                 Tornado       BERKS  04-NOV-50 17:30:00            250K
8                 Tornado      HUGHES  15-SEP-50 17:45:00            250K
9                 Tornado   PITTSBURG  16-SEP-50 01:30:00            .25K
10                Tornado    CIMARRON  01-OCT-50 21:00:00             25K
11                Tornado    NUCKOLLS  22-JUN-50 21:00:00              0K
12                Tornado    OKLAHOMA  27-FEB-50 10:20:00             25K
13                Tornado   PITTSBURG  27-MAR-50 03:00:00            2.5K
14                Tornado     LINCOLN  02-APR-50 18:00:00             25K
15                Tornado       TULSA  03-APR-50 16:15:00            2.5K
16                Tornado       KIOWA  28-APR-50 14:17:00            250K
17                Tornado       KIOWA  28-APR-50 14:35:00            250K
18                Tornado      HUGHES  28-APR-50 19:05:00            250K
19                Tornado        COAL  28-APR-50 19:30:00             25K
20                Tornado      CUSTER  04-MAY-50 21:30:00            2.5K
21                Tornado     BECKHAM  04-MAY-50 21:30:00             25K
22                Tornado    WOODWARD  04-MAY-50 21:45:00            250K
23                Tornado       ELLIS  07-MAY-50 18:30:00              0K
24                Tornado       PAYNE  07-MAY-50 23:00:00            2.5K
25                Tornado  KINGFISHER  07-MAY-50 23:00:00             25K
26                Tornado      RANKIN  27-MAR-50 08:00:00            250K
27                Tornado      RANKIN  27-MAR-50 08:05:00            250K
28                Tornado        CLAY  27-MAR-50 08:45:00              0K
29                Tornado  TISHOMINGO  27-MAR-50 11:00:00             25K
...                   ...         ...                 ...             ...
973019              Flood     FLEMING  23-JUL-17 02:40:00           2.00M
973020        Flash Flood  SANTA CRUZ  17-JUL-17 05:30:00           0.00K
973021  Thunderstorm Wind     GREELEY  08-JUL-17 17:11:00           0.00K
973022               Hail     GREELEY  08-JUL-17 17:40:00           0.00K
973023  Thunderstorm Wind     FORREST  07-JUL-17 16:10:00           5.00K
973024  Thunderstorm Wind   HUMPHREYS  08-JUL-17 08:28:00           5.00K
973025        Flash Flood     FORREST  24-JUL-17 07:02:00           5.00K
973026  Thunderstorm Wind      COPIAH  24-JUL-17 09:40:00           8.00K
973027  Thunderstorm Wind     LINCOLN  24-JUL-17 10:18:00           5.00K
973028        Flash Flood    HERKIMER  01-JUL-17 12:00:00           0.00K
973029        Flash Flood    HERKIMER  01-JUL-17 15:00:00           0.00K
973030  Thunderstorm Wind    HEMPHILL  03-JUL-17 18:24:00           0.00K
973031               Hail      CARSON  03-JUL-17 19:05:00           0.00K
973032               Hail        GRAY  03-JUL-17 19:43:00           0.00K
973033              Flood   MIDDLESEX  12-JUL-17 17:00:00           1.00M
973034               Hail      VALLEY  02-JUL-17 15:20:00           0.00K
973035        Flash Flood    HERKIMER  01-JUL-17 15:10:00           1.00M
973036  Thunderstorm Wind     JACKSON  25-JUL-17 12:00:00           0.00K
973037        Flash Flood     LINCOLN  25-JUL-17 07:27:00         650.00K
973038  Thunderstorm Wind        PIMA  13-JUL-17 19:25:00           0.50K
973039  Thunderstorm Wind      PENDER  06-JUL-17 13:30:00           5.00K
973040               Hail      CORSON  05-JUL-17 16:20:00           0.00K
973041               Hail     EDMUNDS  05-JUL-17 17:26:00           0.00K
973042               Hail       BROWN  05-JUL-17 17:48:00           0.00K
973043               Hail        CLAY  21-AUG-17 01:05:00           0.00K
973044               Hail        LYON  21-AUG-17 10:48:00           0.00K
973045               Hail     OSCEOLA  21-AUG-17 10:57:00           0.00K
973046  Thunderstorm Wind   SAN DIEGO  12-AUG-17 16:25:00          15.00K
973047        Flash Flood   SAN DIEGO  12-AUG-17 16:30:00           5.00K
973048        Flash Flood   SAN DIEGO  12-AUG-17 16:10:00           5.00K

       DAMAGE_CROPS BEGIN_LAT BEGIN_LON DEATHS INJURIES  YEAR  TEMPERATURE
0                 0     35.12    -99.20     00       00  1950        34.94
1                 0     31.90    -98.60     00       00  1950        34.94
2                 0     40.58    -75.70     00       02  1950        34.94
3                 0     40.60    -76.75     00       00  1950        34.94
4                 0     41.63    -79.68     00       00  1950        34.94
5                 0     40.22    -75.00     00       00  1950        34.94
6                 0     40.20    -76.12     00       01  1950        34.94
7                 0     40.27    -76.07     00       00  1950        34.94
8                 0     35.00    -96.25     00       06  1950        34.94
9                 0     34.83    -95.85     00       00  1950        34.94
10                0     36.73   -102.52     00       00  1950        34.94
11                0     40.18    -98.03     00       00  1950        34.94
12                0     35.55    -97.60     00       00  1950        34.94
13                0     34.85    -95.75     00       00  1950        34.94
14                0     35.82    -97.02     00       00  1950        34.94
15                0     36.13    -95.83     00       00  1950        34.94
16                0     34.88    -99.28     10       01  1950        34.94
17                0     35.00    -99.20     00       00  1950        34.94
18                0     35.08    -96.40     50      032  1950        34.94
19                0     34.55    -96.20     00       00  1950        34.94
20                0     35.58    -99.17     00       00  1950        34.94
21                0     35.25    -99.55     00       00  1950        34.94
22                0     36.57    -99.57     00       00  1950        34.94
23                0     36.30    -99.80     00       00  1950        34.94
24                0     36.00    -97.00     00       00  1950        34.94
25                0     36.12    -97.83     00       03  1950        34.94
26                0     32.30    -90.12     00       00  1950        34.94
27                0     32.30    -90.17     00       00  1950        34.94
28                0     33.67    -88.78     00       00  1950        34.94
29                0     34.73    -88.27     00       02  1950        34.94
...             ...       ...       ...    ...      ...   ...          ...
973019        0.00K   38.4269   -83.742      0        0  2017        40.28
973020        0.00K   31.3416  -110.951      0        0  2017        40.28
973021        0.00K      41.4     -98.4      0        0  2017        40.28
973022        0.00K     41.47  -98.7007      0        0  2017        40.28
973023        0.00K     30.96    -89.19      0        0  2017        40.28
973024        0.00K     33.17     -90.5      0        0  2017        40.28
973025        0.00K     30.92    -89.29      0        0  2017        40.28
973026        0.00K     31.84    -90.41      0        0  2017        40.28
973027        0.00K   31.6173  -90.5096      0        0  2017        40.28
973028        0.00K   43.1644  -75.0016      0        0  2017        40.28
973029        0.00K     43.11    -74.98      0        0  2017        40.28
973030        0.00K     35.92   -100.28      0        0  2017        40.28
973031        0.00K     35.57   -101.17      0        0  2017        40.28
973032        0.00K     35.55   -100.96      0        0  2017        40.28
973033        0.00K   42.4637  -71.2925      0        0  2017        40.28
973034        0.00K   41.6277  -98.8406      0        0  2017        40.28
973035        1.00K   43.1083  -75.1561      0        0  2017        40.28
973036        0.00K    30.371  -88.7567      0        0  2017        40.28
973037        0.00K   31.6087  -90.4256      0        0  2017        40.28
973038        0.00K   31.8849  -110.995      0        0  2017        40.28
973039        0.00K   34.4283  -77.6802      0        0  2017        40.28
973040        0.00K     45.65   -100.44      0        0  2017        40.28
973041        0.00K     45.47    -98.75      0        0  2017        40.28
973042        0.00K     45.47    -98.32      0        0  2017        40.28
973043        0.00K     43.14    -94.97      0        0  2017        40.28
973044        0.00K     43.43    -96.17      0        0  2017        40.28
973045        0.00K      43.4    -95.73      0        0  2017        40.28
973046        0.00K   32.9156  -116.244      0        0  2017        40.28
973047        0.00K   32.9181  -116.254      0        0  2017        40.28
973048        0.00K   33.0425  -116.105      0        0  2017        40.28

[973049 rows x 11 columns]

In [82]:
# Find unique/distinct weather events
for storm_event in df.EVENT_TYPE.unique():
    print(storm_event)

Tornado
Hail
Thunderstorm Wind
TORNADOES, TSTM WIND, HAIL
THUNDERSTORM WINDS/FLOODING
HAIL/ICY ROADS
HAIL FLOODING
THUNDERSTORM WINDS/FLASH FLOOD
THUNDERSTORM WINDS LIGHTNING
THUNDERSTORM WIND/ TREES
THUNDERSTORM WIND/ TREE
THUNDERSTORM WINDS FUNNEL CLOU
TORNADO/WATERSPOUT
THUNDERSTORM WINDS/HEAVY RAIN
THUNDERSTORM WINDS HEAVY RAIN
THUNDERSTORM WINDS/ FLOOD
Winter Storm
Cold/Wind Chill
Heavy Snow
Flood
High Wind
Flash Flood
Blizzard
Ice Storm
Lightning
Frost/Freeze
Heavy Rain
Strong Wind
Coastal Flood
Wildfire
High Surf
Funnel Cloud
Winter Weather
Waterspout
Drought
Avalanche
Debris Flow
Heat
Tropical Storm
Dust Devil
Dense Fog
Hurricane (Typhoon)
Storm Surge/Tide
Marine High Wind
Dust Storm
Lake-Effect Snow
Rip Current
Seiche
Extreme Cold/Wind Chill
Excessive Heat
Volcanic Ash
Marine Thunderstorm Wind
Marine Hail
Tsunami
Landslide
Sleet
Marine Strong Wind
Freezing Fog
Lakeshore Flood
Astronomical Low Tide
Tropical Depression
Hurricane
Dense Smoke
Volcanic Ashfall
Sneakerwave
Marine Tropical Storm
Marine Dense Fog
Marine Hurricane/Typhoon
Marine Lightning
Marine Tropical Depression

In [83]:
# group weather events into the following groups
# Tornado, Hail, Thunderstorm, Winter Storm, High Wind, Dust Storm, Hurricane, Heat, Tropical Storm, Drought, Wildfire, Other
df.loc[df['EVENT_TYPE'] == 'Thunderstorm Wind', 'EVENT_TYPE'] = 'Thunderstorm'
df.loc[df['EVENT_TYPE'] == 'TORNADOES, TSTM WIND, HAIL', 'EVENT_TYPE'] = 'Tornado'
df.loc[df['EVENT_TYPE'] == 'THUNDERSTORM WINDS/FLOODING', 'EVENT_TYPE'] = 'Thunderstorm'
df.loc[df['EVENT_TYPE'] == 'HAIL/ICY ROADS', 'EVENT_TYPE'] = 'Hail'
df.loc[df['EVENT_TYPE'] == 'HAIL FLOODING', 'EVENT_TYPE'] = 'Hail'
df.loc[df['EVENT_TYPE'] == 'THUNDERSTORM WINDS/FLASH FLOOD', 'EVENT_TYPE'] = 'Thunderstorm'
df.loc[df['EVENT_TYPE'] == 'THUNDERSTORM WINDS LIGHTNING', 'EVENT_TYPE'] = 'Thunderstorm'
df.loc[df['EVENT_TYPE'] == 'THUNDERSTORM WIND/ TREES', 'EVENT_TYPE'] = 'Thunderstorm'
df.loc[df['EVENT_TYPE'] == 'THUNDERSTORM WIND/ TREE', 'EVENT_TYPE'] = 'Thunderstorm'

df.loc[df['EVENT_TYPE'] == 'TORNADO/WATERSPOUT', 'EVENT_TYPE'] = 'Tornado'
df.loc[df['EVENT_TYPE'] == 'THUNDERSTORM WINDS/HEAVY RAIN', 'EVENT_TYPE'] = 'Thunderstorm'
df.loc[df['EVENT_TYPE'] == 'THUNDERSTORM WINDS HEAVY RAIN', 'EVENT_TYPE'] = 'Thunderstorm'
df.loc[df['EVENT_TYPE'] == 'Cold/Wind Chill', 'EVENT_TYPE'] = 'Winter Storm'
df.loc[df['EVENT_TYPE'] == 'Heavy Snow', 'EVENT_TYPE'] = 'Winter Storm'
df.loc[df['EVENT_TYPE'] == 'Flash Flood', 'EVENT_TYPE'] = 'Flood'
df.loc[df['EVENT_TYPE'] == 'Blizzard', 'EVENT_TYPE'] = 'Winter Storm'
df.loc[df['EVENT_TYPE'] == 'Ice Storm', 'EVENT_TYPE'] = 'Winter Storm'

df.loc[df['EVENT_TYPE'] == 'Lightning', 'EVENT_TYPE'] = 'Thunderstorm'
df.loc[df['EVENT_TYPE'] == 'Frost/Freeze', 'EVENT_TYPE'] = 'Other'
df.loc[df['EVENT_TYPE'] == 'Heavy Rain', 'EVENT_TYPE'] = 'Other'
df.loc[df['EVENT_TYPE'] == 'Strong Wind', 'EVENT_TYPE'] = 'High Wind'
df.loc[df['EVENT_TYPE'] == 'Coastal Flood', 'EVENT_TYPE'] = 'Flood'
df.loc[df['EVENT_TYPE'] == 'High Surf', 'EVENT_TYPE'] = 'Other'
df.loc[df['EVENT_TYPE'] == 'Funnel Cloud', 'EVENT_TYPE'] = 'Other'
df.loc[df['EVENT_TYPE'] == 'Winter Weather', 'EVENT_TYPE'] = 'Winter Storm'
df.loc[df['EVENT_TYPE'] == 'Waterspout', 'EVENT_TYPE'] = 'Other'

df.loc[df['EVENT_TYPE'] == 'Avalanche', 'EVENT_TYPE'] = 'Other'
df.loc[df['EVENT_TYPE'] == 'Debris Flow', 'EVENT_TYPE'] = 'Other'
df.loc[df['EVENT_TYPE'] == 'Dust Devil', 'EVENT_TYPE'] = 'Other'
df.loc[df['EVENT_TYPE'] == 'Dense Fog', 'EVENT_TYPE'] = 'Other'
df.loc[df['EVENT_TYPE'] == 'Lake-Effect Snow', 'EVENT_TYPE'] = 'Winter Storm'
df.loc[df['EVENT_TYPE'] == 'Rip Current', 'EVENT_TYPE'] = 'Other'
df.loc[df['EVENT_TYPE'] == 'Seiche', 'EVENT_TYPE'] = 'Other'
df.loc[df['EVENT_TYPE'] == 'Extreme Cold/Wind Chill', 'EVENT_TYPE'] = 'Winter Storm'
df.loc[df['EVENT_TYPE'] == 'Excessive Heat', 'EVENT_TYPE'] = 'Heat'

df.loc[df['EVENT_TYPE'] == 'Volcanic Ash', 'EVENT_TYPE'] = 'Other'
df.loc[df['EVENT_TYPE'] == 'Marine Thunderstorm Wind', 'EVENT_TYPE'] = 'Other'
df.loc[df['EVENT_TYPE'] == 'Marine Hail', 'EVENT_TYPE'] = 'Other'
df.loc[df['EVENT_TYPE'] == 'Landslide', 'EVENT_TYPE'] = 'Other'
df.loc[df['EVENT_TYPE'] == 'Sleet', 'EVENT_TYPE'] = 'Winter Storm'
df.loc[df['EVENT_TYPE'] == 'Marine Strong Wind', 'EVENT_TYPE'] = 'High Wind'
df.loc[df['EVENT_TYPE'] == 'Freezing Fog', 'EVENT_TYPE'] = 'Other'
df.loc[df['EVENT_TYPE'] == 'Lakeshore Flood', 'EVENT_TYPE'] = 'Flood'

df.loc[df['EVENT_TYPE'] == 'Tropical Depression', 'EVENT_TYPE'] = 'Other'
df.loc[df['EVENT_TYPE'] == 'Dense Smoke', 'EVENT_TYPE'] = 'Other'
df.loc[df['EVENT_TYPE'] == 'Volcanic Ashfall', 'EVENT_TYPE'] = 'Other'
df.loc[df['EVENT_TYPE'] == 'Sneakerwave', 'EVENT_TYPE'] = 'Other'
df.loc[df['EVENT_TYPE'] == 'Marine Tropical Storm', 'EVENT_TYPE'] = 'Tropical Storm'
df.loc[df['EVENT_TYPE'] == 'Marine Dense Fog', 'EVENT_TYPE'] = 'Other'
df.loc[df['EVENT_TYPE'] == 'Marine Hurricane/Typhoon', 'EVENT_TYPE'] = 'Other'
df.loc[df['EVENT_TYPE'] == 'Marine Lightning', 'EVENT_TYPE'] = 'Other'

df.loc[df['EVENT_TYPE'] == 'Marine Tropical Depression', 'EVENT_TYPE'] = 'Other'
df.loc[df['EVENT_TYPE'] == 'THUNDERSTORM WINDS FUNNEL CLOU', 'EVENT_TYPE'] = 'Thunderstorm'
df.loc[df['EVENT_TYPE'] == 'THUNDERSTORM WINDS/ FLOOD', 'EVENT_TYPE'] = 'Thunderstorm'
df.loc[df['EVENT_TYPE'] == 'Hurricane (Typhoon)', 'EVENT_TYPE'] = 'Hurricane'
df.loc[df['EVENT_TYPE'] == 'Storm Surge/Tide', 'EVENT_TYPE'] = 'Other'
df.loc[df['EVENT_TYPE'] == 'Marine High Wind', 'EVENT_TYPE'] = 'Other'
df.loc[df['EVENT_TYPE'] == 'Astronomical Low Tide', 'EVENT_TYPE'] = 'Other'
df.loc[df['EVENT_TYPE'] == 'Dust Storm', 'EVENT_TYPE'] = 'Other'
print(df.EVENT_TYPE.unique())

['Tornado' 'Hail' 'Thunderstorm' 'Winter Storm' 'Flood' 'High Wind' 'Other'
 'Wildfire' 'Drought' 'Heat' 'Tropical Storm' 'Hurricane' 'Tsunami']

In [84]:
print(df.dtypes)

EVENT_TYPE          object
NAME                object
DATE                object
DAMAGE_PROPERTY     object
DAMAGE_CROPS        object
BEGIN_LAT           object
BEGIN_LON           object
DEATHS              object
INJURIES            object
YEAR                object
TEMPERATURE        float64
dtype: object

In [85]:
df[['EVENT_TYPE', 'NAME']] = df[['EVENT_TYPE', 'NAME']].astype('str')
df[['DEATHS', 'INJURIES']] = df[['DEATHS', 'INJURIES']].astype('int64')
df[['BEGIN_LAT','BEGIN_LON']] = df[['BEGIN_LAT','BEGIN_LON']].astype('float')

print(df.dtypes)

EVENT_TYPE          object
NAME                object
DATE                object
DAMAGE_PROPERTY     object
DAMAGE_CROPS        object
BEGIN_LAT          float64
BEGIN_LON          float64
DEATHS               int64
INJURIES             int64
YEAR                object
TEMPERATURE        float64
dtype: object

In [86]:
def ProcessNumeral(value):
    value = str(value)
    if('K' in value or 'k' in value):
        if value == 'K' or value == 'k':
            return 0
        value = value.replace('K','')
        value = value.replace('k','')
        return float(value)*1000
    elif('M' in value or 'm' in value):
        if value == 'M' or value == 'm':
            return 0
        value = value.replace('M','')
        value = value.replace('m','')
        return float(value)*1000000
    elif('B' in value or 'b' in value):
        if value == 'B' or value == 'b':
            return 0
        value = value.replace('B','')
        value = value.replace('b','')
        return float(value)*1000000000
    elif(value == '0'):
        return 0
    else:
        if isinstance(value, float):
            return value
        #print(value)
        return 0

df['DAMAGE_PROPERTY'] = [ProcessNumeral(value) for value in df['DAMAGE_PROPERTY']]
df['DAMAGE_CROPS'] = [ProcessNumeral(value) for value in df['DAMAGE_CROPS']]

df[['DAMAGE_PROPERTY','DAMAGE_CROPS']] = df[['DAMAGE_PROPERTY','DAMAGE_CROPS']].astype('float64')
print(df.dtypes)

EVENT_TYPE          object
NAME                object
DATE                object
DAMAGE_PROPERTY    float64
DAMAGE_CROPS       float64
BEGIN_LAT          float64
BEGIN_LON          float64
DEATHS               int64
INJURIES             int64
YEAR                object
TEMPERATURE        float64
dtype: object

In [ ]:
years = list(range(1950, 2018))
print(years)
cols = ['NAME', 'YEAR', 'EVENT_TYPE', 'DEATHS', 'INJURIES', 'DAMAGE_PROPERTY', 'TEMPERATURE', 'DATE']
Worst_Property_Damage = pd.DataFrame(columns = cols)
for year in years:
    for event in df.EVENT_TYPE.unique():
        dfYear = df.loc[df['YEAR'] == str(year), cols]
        worst = dfYear[dfYear['EVENT_TYPE'] == event].sort_values('DAMAGE_PROPERTY', ascending = False)
        worst = worst.head(10)
        Worst_Property_Damage = Worst_Property_Damage.append(worst)
        
print(Worst_Property_Damage)
Worst_Property_Damage.to_csv(path_or_buf = 'C:\\Users\\Benjamin\\Desktop\\Storm_allyears\\Worst_Property_Damage.csv')

[1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]

In [ ]:
years = list(range(1950, 2018))
print(years)
cols = ['YEAR', 'EVENT_TYPE', 'DEATHS', 'INJURIES', 'DAMAGE_PROPERTY', 'TEMPERATURE']
Worst_Deaths = pd.DataFrame(columns = cols)
for year in years:
    for event in df.EVENT_TYPE.unique():
        dfYear = df.loc[df['YEAR'] == str(year), cols]
        worst = dfYear[dfYear['EVENT_TYPE'] == event].sort_values('DEATHS', ascending = False)
        worst = worst.head(10)
        Worst_Deaths = Worst_Deaths.append(worst)
        
print(Worst_Deaths)
Worst_Deaths.to_csv(path_or_buf = 'C:\\Users\\Benjamin\\Desktop\\Storm_allyears\\Worst_Deaths.csv')

In [15]:
df.to_csv(path_or_buf = 'C:\\Users\\Benjamin\\Desktop\\Storm_allyears\\Processed_Storm_Data.csv')